version: '3.3'
services:
  app:
    build: .
    volumes:
      - ./:/opt/app
    command: python3 server.py
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/million.conf:ro
      - ./www/:/var/www:ro
    ports:
      - 8080:80
    depends_on:
      - app
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/etc/mongo
