version: '3.3'
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/million.conf:ro
      - ./www/:/var/www:ro
    ports:
      - 80:80
    depends_on:
      - app
  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/etc/mongo
